import { Injectable, signal } from '@angular/core';
import { DAYS } from '../constants';
import { Stock } from '../models/stock';

@Injectable({
  providedIn: 'root',
})
export class WallStreetService {
  private stockPrices = signal<{
    [key: string]: Stock[];
  }>({
    [DAYS.DAY_ONE]: [
      { symbol: 'AAPL', gain: -0.05 },
      { symbol: 'GOOGL', gain: 0.1 },
      { symbol: 'TSLA', gain: -0.15 },
      { symbol: 'AMZN', gain: 0.2 },
      { symbol: 'MSFT', gain: -0.05 },
      { symbol: 'FB', gain: 0.1 },
      { symbol: 'TWTR', gain: -0.02 },
      { symbol: 'NFLX', gain: 0.1 },
      { symbol: 'NVDA', gain: -0.05 },
      { symbol: 'INTC', gain: -0.02 },
      { symbol: 'AMD', gain: 0.03 },
      { symbol: 'QCOM', gain: -0.05 },
      { symbol: 'IBM', gain: -0.02 },
      { symbol: 'ORCL', gain: -0.02 },
      { symbol: 'CSCO', gain: -0.02 },
      { symbol: 'CRM', gain: 0.1 },
      { symbol: 'ADBE', gain: 0.1 },
      { symbol: 'PYPL', gain: -0.05 },
      { symbol: 'SQ', gain: -0.05 },
      { symbol: 'SHOP', gain: 0.15 },
      { symbol: 'SNOW', gain: -0.05 },
      { symbol: 'ZM', gain: -0.05 },
      { symbol: 'UBER', gain: -0.02 },
      { symbol: 'LYFT', gain: -0.02 },
      { symbol: 'T', gain: 0.01 },
      { symbol: 'VZ', gain: -0.02 },
      { symbol: 'TMUS', gain: -0.05 },
      { symbol: 'S', gain: 0.01 },
      { symbol: 'TM', gain: -0.05 },
      { symbol: 'F', gain: 0.01 },
      { symbol: 'GM', gain: -0.02 },
      { symbol: 'FCAU', gain: 0.01 },
      { symbol: 'FORD', gain: 0.01 },
      { symbol: 'HMC', gain: -0.02 },
      { symbol: 'NSANY', gain: 0.01 },
      { symbol: 'VWAGY', gain: -0.03 },
    ],
    [DAYS.DAY_TWO]: [
      { symbol: 'AAPL', gain: -0.05 },
      { symbol: 'GOOGL', gain: 0.1 },
      { symbol: 'TSLA', gain: -0.15 },
      { symbol: 'AMZN', gain: 0.2 },
      { symbol: 'MSFT', gain: -0.05 },
      { symbol: 'FB', gain: 0.1 },
      { symbol: 'TWTR', gain: -0.02 },
      { symbol: 'NFLX', gain: 0.1 },
      { symbol: 'NVDA', gain: -0.05 },
      { symbol: 'INTC', gain: -0.02 },
      { symbol: 'AMD', gain: 0.03 },
      { symbol: 'QCOM', gain: -0.05 },
      { symbol: 'IBM', gain: -0.02 },
      { symbol: 'ORCL', gain: -0.02 },
      { symbol: 'CSCO', gain: -0.02 },
      { symbol: 'CRM', gain: 0.1 },
      { symbol: 'ADBE', gain: 0.1 },
      { symbol: 'PYPL', gain: -0.05 },
      { symbol: 'SQ', gain: -0.05 },
      { symbol: 'SHOP', gain: 0.15 },
      { symbol: 'SNOW', gain: -0.05 },
      { symbol: 'ZM', gain: -0.05 },
      { symbol: 'UBER', gain: -0.02 },
      { symbol: 'LYFT', gain: -0.02 },
      { symbol: 'T', gain: 0.01 },
      { symbol: 'VZ', gain: -0.02 },
      { symbol: 'TMUS', gain: -0.05 },
      { symbol: 'S', gain: 0.01 },
      { symbol: 'TM', gain: -0.05 },
      { symbol: 'F', gain: 0.01 },
      { symbol: 'GM', gain: -0.02 },
      { symbol: 'FCAU', gain: 0.01 },
      { symbol: 'FORD', gain: 0.01 },
      { symbol: 'HMC', gain: -0.02 },
      { symbol: 'NSANY', gain: 0.01 },
      { symbol: 'VWAGY', gain: -0.03 },
    ],
    [DAYS.DAY_THREE]: [
      { symbol: 'AAPL', gain: -0.05 },
      { symbol: 'GOOGL', gain: 0.1 },
      { symbol: 'TSLA', gain: -0.15 },
      { symbol: 'AMZN', gain: 0.2 },
      { symbol: 'MSFT', gain: -0.05 },
      { symbol: 'FB', gain: 0.1 },
      { symbol: 'TWTR', gain: -0.02 },
      { symbol: 'NFLX', gain: 0.1 },
      { symbol: 'NVDA', gain: -0.05 },
      { symbol: 'INTC', gain: -0.02 },
      { symbol: 'AMD', gain: 0.03 },
      { symbol: 'QCOM', gain: -0.05 },
      { symbol: 'IBM', gain: -0.02 },
      { symbol: 'ORCL', gain: -0.02 },
      { symbol: 'CSCO', gain: -0.02 },
      { symbol: 'CRM', gain: 0.1 },
      { symbol: 'ADBE', gain: 0.1 },
      { symbol: 'PYPL', gain: -0.05 },
      { symbol: 'SQ', gain: -0.05 },
      { symbol: 'SHOP', gain: 0.15 },
      { symbol: 'SNOW', gain: -0.05 },
      { symbol: 'ZM', gain: -0.05 },
      { symbol: 'UBER', gain: -0.02 },
      { symbol: 'LYFT', gain: -0.02 },
      { symbol: 'T', gain: 0.01 },
      { symbol: 'VZ', gain: -0.02 },
      { symbol: 'TMUS', gain: -0.05 },
      { symbol: 'S', gain: 0.01 },
      { symbol: 'TM', gain: -0.05 },
      { symbol: 'F', gain: 0.01 },
      { symbol: 'GM', gain: -0.02 },
      { symbol: 'FCAU', gain: 0.01 },
      { symbol: 'FORD', gain: 0.01 },
      { symbol: 'HMC', gain: -0.02 },
      { symbol: 'NSANY', gain: 0.01 },
      { symbol: 'VWAGY', gain: -0.03 },
    ],
    [DAYS.DAY_FOUR]: [
      { symbol: 'AAPL', gain: -0.05 },
      { symbol: 'GOOGL', gain: 0.1 },
      { symbol: 'TSLA', gain: -0.15 },
      { symbol: 'AMZN', gain: 0.2 },
      { symbol: 'MSFT', gain: -0.05 },
      { symbol: 'FB', gain: 0.1 },
      { symbol: 'TWTR', gain: -0.02 },
      { symbol: 'NFLX', gain: 0.1 },
      { symbol: 'NVDA', gain: -0.05 },
      { symbol: 'INTC', gain: -0.02 },
      { symbol: 'AMD', gain: 0.03 },
      { symbol: 'QCOM', gain: -0.05 },
      { symbol: 'IBM', gain: -0.02 },
      { symbol: 'ORCL', gain: -0.02 },
      { symbol: 'CSCO', gain: -0.02 },
      { symbol: 'CRM', gain: 0.1 },
      { symbol: 'ADBE', gain: 0.1 },
      { symbol: 'PYPL', gain: -0.05 },
      { symbol: 'SQ', gain: -0.05 },
      { symbol: 'SHOP', gain: 0.15 },
      { symbol: 'SNOW', gain: -0.05 },
      { symbol: 'ZM', gain: -0.05 },
      { symbol: 'UBER', gain: -0.02 },
      { symbol: 'LYFT', gain: -0.02 },
      { symbol: 'T', gain: 0.01 },
      { symbol: 'VZ', gain: -0.02 },
      { symbol: 'TMUS', gain: -0.05 },
      { symbol: 'S', gain: 0.01 },
      { symbol: 'TM', gain: -0.05 },
      { symbol: 'F', gain: 0.01 },
      { symbol: 'GM', gain: -0.02 },
      { symbol: 'FCAU', gain: 0.01 },
      { symbol: 'FORD', gain: 0.01 },
      { symbol: 'HMC', gain: -0.02 },
      { symbol: 'NSANY', gain: 0.01 },
      { symbol: 'VWAGY', gain: -0.03 },
    ],
    [DAYS.DAY_FIVE]: [
      { symbol: 'AAPL', gain: -0.05 },
      { symbol: 'GOOGL', gain: 0.1 },
      { symbol: 'TSLA', gain: -0.15 },
      { symbol: 'AMZN', gain: 0.2 },
      { symbol: 'MSFT', gain: -0.05 },
      { symbol: 'FB', gain: 0.1 },
      { symbol: 'TWTR', gain: -0.02 },
      { symbol: 'NFLX', gain: 0.1 },
      { symbol: 'NVDA', gain: -0.05 },
      { symbol: 'INTC', gain: -0.02 },
      { symbol: 'AMD', gain: 0.03 },
      { symbol: 'QCOM', gain: -0.05 },
      { symbol: 'IBM', gain: -0.02 },
      { symbol: 'ORCL', gain: -0.02 },
      { symbol: 'CSCO', gain: -0.02 },
      { symbol: 'CRM', gain: 0.1 },
      { symbol: 'ADBE', gain: 0.1 },
      { symbol: 'PYPL', gain: -0.05 },
      { symbol: 'SQ', gain: -0.05 },
      { symbol: 'SHOP', gain: 0.15 },
      { symbol: 'SNOW', gain: -0.05 },
      { symbol: 'ZM', gain: -0.05 },
      { symbol: 'UBER', gain: -0.02 },
      { symbol: 'LYFT', gain: -0.02 },
      { symbol: 'T', gain: 0.01 },
      { symbol: 'VZ', gain: -0.02 },
      { symbol: 'TMUS', gain: -0.05 },
      { symbol: 'S', gain: 0.01 },
      { symbol: 'TM', gain: -0.05 },
      { symbol: 'F', gain: 0.01 },
      { symbol: 'GM', gain: -0.02 },
      { symbol: 'FCAU', gain: 0.01 },
      { symbol: 'FORD', gain: 0.01 },
      { symbol: 'HMC', gain: -0.02 },
      { symbol: 'NSANY', gain: 0.01 },
      { symbol: 'VWAGY', gain: -0.03 },
    ],
    [DAYS.DAY_SIX]: [
      { symbol: 'AAPL', gain: -0.05 },
      { symbol: 'GOOGL', gain: 0.1 },
      { symbol: 'TSLA', gain: -0.15 },
      { symbol: 'AMZN', gain: 0.2 },
      { symbol: 'MSFT', gain: -0.05 },
      { symbol: 'FB', gain: 0.1 },
      { symbol: 'TWTR', gain: -0.02 },
      { symbol: 'NFLX', gain: 0.1 },
      { symbol: 'NVDA', gain: -0.05 },
      { symbol: 'INTC', gain: -0.02 },
      { symbol: 'AMD', gain: 0.03 },
      { symbol: 'QCOM', gain: -0.05 },
      { symbol: 'IBM', gain: -0.02 },
      { symbol: 'ORCL', gain: -0.02 },
      { symbol: 'CSCO', gain: -0.02 },
      { symbol: 'CRM', gain: 0.1 },
      { symbol: 'ADBE', gain: 0.1 },
      { symbol: 'PYPL', gain: -0.05 },
      { symbol: 'SQ', gain: -0.05 },
      { symbol: 'SHOP', gain: 0.15 },
      { symbol: 'SNOW', gain: -0.05 },
      { symbol: 'ZM', gain: -0.05 },
      { symbol: 'UBER', gain: -0.02 },
      { symbol: 'LYFT', gain: -0.02 },
      { symbol: 'T', gain: 0.01 },
      { symbol: 'VZ', gain: -0.02 },
      { symbol: 'TMUS', gain: -0.05 },
      { symbol: 'S', gain: 0.01 },
      { symbol: 'TM', gain: -0.05 },
      { symbol: 'F', gain: 0.01 },
      { symbol: 'GM', gain: -0.02 },
      { symbol: 'FCAU', gain: 0.01 },
      { symbol: 'FORD', gain: 0.01 },
      { symbol: 'HMC', gain: -0.02 },
      { symbol: 'NSANY', gain: 0.01 },
      { symbol: 'VWAGY', gain: -0.03 },
    ],
    [DAYS.DAY_SEVEN]: [
      { symbol: 'AAPL', gain: -0.05 },
      { symbol: 'GOOGL', gain: 0.1 },
      { symbol: 'TSLA', gain: -0.15 },
      { symbol: 'AMZN', gain: 0.2 },
      { symbol: 'MSFT', gain: -0.05 },
      { symbol: 'FB', gain: 0.1 },
      { symbol: 'TWTR', gain: -0.02 },
      { symbol: 'NFLX', gain: 0.1 },
      { symbol: 'NVDA', gain: -0.05 },
      { symbol: 'INTC', gain: -0.02 },
      { symbol: 'AMD', gain: 0.03 },
      { symbol: 'QCOM', gain: -0.05 },
      { symbol: 'IBM', gain: -0.02 },
      { symbol: 'ORCL', gain: -0.02 },
      { symbol: 'CSCO', gain: -0.02 },
      { symbol: 'CRM', gain: 0.1 },
      { symbol: 'ADBE', gain: 0.1 },
      { symbol: 'PYPL', gain: -0.05 },
      { symbol: 'SQ', gain: -0.05 },
      { symbol: 'SHOP', gain: 0.15 },
      { symbol: 'SNOW', gain: -0.05 },
      { symbol: 'ZM', gain: -0.05 },
      { symbol: 'UBER', gain: -0.02 },
      { symbol: 'LYFT', gain: -0.02 },
      { symbol: 'T', gain: 0.01 },
      { symbol: 'VZ', gain: -0.02 },
      { symbol: 'TMUS', gain: -0.05 },
      { symbol: 'S', gain: 0.01 },
      { symbol: 'TM', gain: -0.05 },
      { symbol: 'F', gain: 0.01 },
      { symbol: 'GM', gain: -0.02 },
      { symbol: 'FCAU', gain: 0.01 },
      { symbol: 'FORD', gain: 0.01 },
      { symbol: 'HMC', gain: -0.02 },
      { symbol: 'NSANY', gain: 0.01 },
      { symbol: 'VWAGY', gain: -0.03 },
    ],
  });

  getStocks(day: DAYS) {
    return this.stockPrices()[day];
  }
}
